plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'kotlin-kapt'
    id 'androidx.navigation.safeargs.kotlin'
    id 'com.google.dagger.hilt.android'
}
def properties = new Properties()
properties.load(rootProject.file("local.properties").newDataInputStream())

android {
    namespace 'com.keremkulac.okeyscore'
    compileSdk 35

    defaultConfig {
        applicationId 'com.keremkulac.okeyscore'
        minSdk 26
        targetSdk 35
        versionCode 21
        versionName "2.3"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        resConfigs "en", "tr"
        javaCompileOptions {
            annotationProcessorOptions {
                arguments += ["room.schemaLocation": "$projectDir/schemas".toString()]
            }
        }
        manifestPlaceholders = [admobAppId: properties.getProperty("ADMOB_APP_ID")]
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            resValue "string", "ad_unit_id", "\"${properties.getProperty("BANNER_AD_UNIT_ID_RELEASE")}\""
            resValue "string", "interstitial_ad_id", "\"${properties.getProperty("INTERSTITIAL_AD_UNIT_ID_RELEASE")}\""
        }
        debug {
            resValue "string", "ad_unit_id", "ca-app-pub-3940256099942544/6300978111"
            resValue "string", "interstitial_ad_id", "ca-app-pub-3940256099942544/1033173712"
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }
    buildFeatures {
        buildConfig = true
        viewBinding = true
        dataBinding = true
    }
}


dependencies {

    implementation 'androidx.core:core-ktx:1.16.0'
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'androidx.lifecycle:lifecycle-livedata-ktx:2.9.1'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.9.1'

    implementation 'androidx.navigation:navigation-fragment-ktx:2.9.0'
    implementation 'androidx.navigation:navigation-ui-ktx:2.9.0'

    implementation 'androidx.test:core-ktx:1.6.1'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.6.1'
    implementation 'com.squareup.retrofit2:retrofit:2.9.0'
    implementation 'com.google.code.gson:gson:2.11.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.9.0'
    implementation 'com.google.dagger:hilt-android:2.56.1'
    kapt 'com.google.dagger:hilt-android-compiler:2.56.1'

    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.9.1'
    implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.9.1'
    implementation 'androidx.activity:activity-ktx:1.10.1'
    implementation 'androidx.fragment:fragment-ktx:1.8.8'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.9.1'
    implementation 'androidx.lifecycle:lifecycle-livedata-ktx:2.9.1'
    implementation 'androidx.lifecycle:lifecycle-common-java8:2.9.1'

    implementation 'androidx.room:room-common:2.7.2'
    implementation 'androidx.room:room-runtime:2.7.2'
    kapt 'androidx.room:room-compiler:2.7.2'
    implementation 'androidx.room:room-ktx:2.7.2'
    implementation 'it.xabaras.android:recyclerview-swipedecorator:1.4'
    implementation 'at.blogc:expandabletextview:1.0.5'
    implementation 'com.tbuonomo:dotsindicator:5.0'
    implementation 'com.google.android.play:review:2.0.2'
    implementation 'com.google.android.play:app-update:2.1.0'
    implementation 'com.google.android.play:app-update-ktx:2.1.0'
    implementation 'com.facebook.shimmer:shimmer:0.5.0'
    implementation 'com.google.android.gms:play-services-ads:24.4.0'

}